// Generated by Codex.
// Explain the fallback.
/*
 * Preserve the fallback.
 */
interface Item {
  active: boolean;
  size: number;
}

interface User {
  id: string;
  name: string;
}

export function canInvite(isActive: boolean, isLocked: boolean): boolean {
  if (isActive && !isLocked) {
    return true;
  }

  return false;
}

export function hasLargeActiveItem(items: Item[]): boolean {
  return items
    .filter((item) => item.active)
    .map((item) => item.size)
    .some((size) => size > 100);
}

export function increment(count: number): number {
  return (count += 1);
}

export function isReady(ready: boolean): boolean {
  return ready === true ? true : false;
}

export function optionalValue(value: string | undefined): string | undefined {
  return value ?? undefined;
}

export const fetchAccount = (id: string) => fetchUser(id);

export function names(users: User[]): string[] {
  return users.map((user) => {
    return user.name;
  });
}

export function publish(user: User | null): void {
  if (user) {
    deliver(user);
    run();
  }
}

export function runWhenReady(status: string): void {
  const isNotReady = status !== "ready";
  if (!isNotReady) {
    run();
  }
}

declare function deliver(user: User): void;
declare function fetchUser(id: string): User;
declare function run(): void;

export function deeplyNested(first: boolean, second: boolean, third: boolean, fourth: boolean): void {
  if (first) {
    if (second) {
      if (third) {
        if (fourth) {
          run();
        }
      }
    }
  }
}
